[package]
name = "mdnsd"
version = "0.1.0"
edition = "2024"

[dependencies]
libmdns = "0.10"
if-addrs = "0.14"
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["macros", "rt", "signal", "time"] }
